name: Build app and deploy to ec2

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
jobs:
  build:
    name: build image on docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make nginx config
        env:
          NGINX_CONFIG: ${{ secrets.NGINX_CONFIG }}
        run: |
          mkdir .nginx
          echo "$NGINX_CONFIG" >> .nginx/nginx.conf
      - name: build docker
        run: docker build -t fakhriinaufal/bayareen-frontend-customer:latest .
      - name: login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: push image to dockerhub registry
        run: docker push fakhriinaufal/bayareen-frontend-customer:latest
  
  deploy:
    name: deploy to ec2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker container rm bayareen-frontend-customer
            docker image rm fakhriinaufal/bayareen-frontend-customer:latest
            docker pull fakhriinaufal/bayareen-frontend-customer:latest
            docker create --name bayareen-frontend-customer -p 3001:80 fakhriinaufal/bayareen-frontend-customer:latest
            docker container start bayareen-frontend-customer